<?php

namespace Database\Seeders;

use App\Models\Area;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $defaultPassword = '123456';

        $users = [
            [
                'name' => 'Administrador General',
                'email' => 'administradoror@redaviation.com',
                'password' => $defaultPassword,
                'area_codigo' => 0,
                'rol' => 'admin',
                'rol_nombre' => 'admin',
                'puesto' => 'Administrador General',
                'telefono' => '555-000-0001',
                'estado' => 'Activo',
                'permisos' => ['usuarios_crud', 'clientes_crud'],
            ],
            [
                'name' => 'Supervisor General',
                'email' => 'supervisor@redaviation.com',
                'password' => $defaultPassword,
                'area_codigo' => 0,
                'rol' => 'supervisor',
                'rol_nombre' => 'supervisor',
                'puesto' => 'Supervisor General',
                'telefono' => '555-000-0002',
                'estado' => 'Activo',
                'permisos' => ['clientes_crud'],
            ],
            [
                'name' => 'Administracion Inventario',
                'email' => 'administracion@redaviation.com',
                'password' => $defaultPassword,
                'area_codigo' => 0,
                'rol' => 'administracion',
                'rol_nombre' => 'administracion',
                'puesto' => 'Administracion',
                'telefono' => '555-000-0003',
                'estado' => 'Activo',
                'permisos' => [],
            ],
            [
                'name' => 'Ingenieria',
                'email' => 'ing@redaviation.com',
                'password' => $defaultPassword,
                'area_codigo' => 'AVCS',
                'rol' => 'tecnico',
                'rol_nombre' => 'ingenieria',
                'puesto' => 'Ingenieria',
                'telefono' => '555-000-0004',
                'estado' => 'Activo',
                'permisos' => ['aeronaves_crud', 'usuarios_crud', 'clientes_crud'],
            ],
            [
                'name' => 'Usuario AVCS',
                'email' => 'avcs@redaviation.com',
                'password' => $defaultPassword,
                'area_codigo' => 'AVCS',
                'rol' => 'tecnico',
                'rol_nombre' => 'tecnico_area',
                'puesto' => 'Tecnico',
                'telefono' => '555-000-0010',
                'estado' => 'Activo',
                'permisos' => [],
            ],
            [
                'name' => 'Usuario HANG',
                'email' => 'hang@redaviation.com',
                'password' => $defaultPassword,
                'area_codigo' => 'HANG',
                'rol' => 'tecnico',
                'rol_nombre' => 'tecnico_area',
                'puesto' => 'Tecnico',
                'telefono' => '555-000-0011',
                'estado' => 'Activo',
                'permisos' => [],
            ],
            [
                'name' => 'Usuario BATT',
                'email' => 'batt@redaviation.com',
                'password' => $defaultPassword,
                'area_codigo' => 'BATT',
                'rol' => 'tecnico',
                'rol_nombre' => 'tecnico_area',
                'puesto' => 'Tecnico',
                'telefono' => '555-000-0012',
                'estado' => 'Activo',
                'permisos' => [],
            ],
            [
                'name' => 'Usuario FREN',
                'email' => 'fren@redaviation.com',
                'password' => $defaultPassword,
                'area_codigo' => 'FREN',
                'rol' => 'tecnico',
                'rol_nombre' => 'tecnico_area',
                'puesto' => 'Tecnico',
                'telefono' => '555-000-0013',
                'estado' => 'Activo',
                'permisos' => [],
            ],
            [
                'name' => 'Usuario TREN',
                'email' => 'tren@redaviation.com',
                'password' => $defaultPassword,
                'area_codigo' => 'TREN',
                'rol' => 'tecnico',
                'rol_nombre' => 'tecnico_area',
                'puesto' => 'Tecnico',
                'telefono' => '555-000-0014',
                'estado' => 'Activo',
                'permisos' => [],
            ],
            [
                'name' => 'Usuario HELI',
                'email' => 'heli@redaviation.com',
                'password' => $defaultPassword,
                'area_codigo' => 'HELI',
                'rol' => 'tecnico',
                'rol_nombre' => 'tecnico_area',
                'puesto' => 'Tecnico',
                'telefono' => '555-000-0015',
                'estado' => 'Activo',
                'permisos' => [],
            ],
            [
                'name' => 'Usuario PROP',
                'email' => 'prop@redaviation.com',
                'password' => $defaultPassword,
                'area_codigo' => 'PROP',
                'rol' => 'tecnico',
                'rol_nombre' => 'tecnico_area',
                'puesto' => 'Tecnico',
                'telefono' => '555-000-0016',
                'estado' => 'Activo',
                'permisos' => [],
            ],
            [
                'name' => 'Usuario PIST',
                'email' => 'pist@redaviation.com',
                'password' => $defaultPassword,
                'area_codigo' => 'PIST',
                'rol' => 'tecnico',
                'rol_nombre' => 'tecnico_area',
                'puesto' => 'Tecnico',
                'telefono' => '555-000-0017',
                'estado' => 'Activo',
                'permisos' => [],
            ],
            [
                'name' => 'Usuario VEST',
                'email' => 'vest@redaviation.com',
                'password' => $defaultPassword,
                'area_codigo' => 'VEST',
                'rol' => 'tecnico',
                'rol_nombre' => 'tecnico_area',
                'puesto' => 'Tecnico',
                'telefono' => '555-000-0018',
                'estado' => 'Activo',
                'permisos' => [],
            ],
            [
                'name' => 'Usuario ESTR',
                'email' => 'estr@redaviation.com',
                'password' => $defaultPassword,
                'area_codigo' => 'ESTR',
                'rol' => 'tecnico',
                'rol_nombre' => 'tecnico_area',
                'puesto' => 'Tecnico',
                'telefono' => '555-000-0019',
                'estado' => 'Activo',
                'permisos' => [],
            ],
            [
                'name' => 'Usuario TORN',
                'email' => 'torn@redaviation.com',
                'password' => $defaultPassword,
                'area_codigo' => 'TORN',
                'rol' => 'tecnico',
                'rol_nombre' => 'tecnico_area',
                'puesto' => 'Tecnico',
                'telefono' => '555-000-0020',
                'estado' => 'Activo',
                'permisos' => [],
            ],
            [
                'name' => 'Usuario SALV',
                'email' => 'salv@redaviation.com',
                'password' => $defaultPassword,
                'area_codigo' => 'SALV',
                'rol' => 'tecnico',
                'rol_nombre' => 'tecnico_area',
                'puesto' => 'Tecnico',
                'telefono' => '555-000-0021',
                'estado' => 'Activo',
                'permisos' => [],
            ],
            [
                'name' => 'Usuario SOLD',
                'email' => 'sold@redaviation.com',
                'password' => $defaultPassword,
                'area_codigo' => 'SOLD',
                'rol' => 'tecnico',
                'rol_nombre' => 'tecnico_area',
                'puesto' => 'Tecnico',
                'telefono' => '555-000-0022',
                'estado' => 'Activo',
                'permisos' => [],
            ],
            [
                'name' => 'Kevin',
                'email' => 'kevin@test.com',
                'password' => $defaultPassword,
                'area_codigo' => 'AVCS',
                'rol' => 'admin',
                'rol_nombre' => 'admin',
                'puesto' => 'Administrador',
                'telefono' => '555-000-0099',
                'estado' => 'Activo',
                'permisos' => ['usuarios_crud', 'clientes_crud'],
            ],
        ];

        foreach ($users as $userData) {
            User::updateOrCreate(
                ['email' => $userData['email']],
                [
                    'name' => $userData['name'],
                    'password' => Hash::make($userData['password']),
                    'area_id' => $userData['area_codigo']
                        ? Area::where('codigo', $userData['area_codigo'])->value('id')
                        : null,
                    'rol' => $userData['rol'],
                    'rol_nombre' => $userData['rol_nombre'] ?? $userData['rol'],
                    'telefono' => $userData['telefono'] ?? null,
                    'puesto' => $userData['puesto'] ?? null,
                    'estado' => $userData['estado'] ?? 'Activo',
                    'permisos' => $userData['permisos'] ?? [],
                ]
            );
        }
    }
}
